CREATE TABLE shopuser (
  id INT NOT NULL ,
  firstName VARCHAR(20) NULL DEFAULT NULL,
  middleName VARCHAR(20) NULL DEFAULT NULL,
  lastName VARCHAR(20) NULL DEFAULT NULL,
  mobile VARCHAR(20) NULL,
  email VARCHAR(40) NULL,
  passwordHash VARCHAR(20) NOT NULL,
  admin INT  NOT NULL DEFAULT 0,
  vendor INT  NOT NULL DEFAULT 0,
  registeredAt DATETIME NOT NULL,
  lastLogin DATETIME NULL DEFAULT NULL,
  intro TEXT NULL DEFAULT NULL,
  profile TEXT NULL DEFAULT NULL,
  PRIMARY KEY (id)
  )
  sp_help shopuser

  CREATE TABLE shopproduct (
  id INT NOT NULL ,
  userId BIGINT NOT NULL,
  title VARCHAR(20) NOT NULL,
  metaTitle VARCHAR(40) NULL,
  slug VARCHAR(20) NOT NULL,
  summary TEXT NULL,
  type SMALLINT NOT NULL DEFAULT 0,
  sku VARCHAR(20) NOT NULL,
  price FLOAT NOT NULL DEFAULT 0,
  discount FLOAT NOT NULL DEFAULT 0,
  quantity SMALLINT NOT NULL DEFAULT 0,
  shop TINYINT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NULL DEFAULT NULL,
  publishedAt DATETIME NULL DEFAULT NULL,
  startsAt DATETIME NULL DEFAULT NULL,
  endsAt DATETIME NULL DEFAULT NULL,
  content TEXT NULL DEFAULT NULL,
  PRIMARY KEY (id),
  )

sp_help shopproduct

CREATE TABLE shopcategory (
  id INT NOT NULL ,
  parentId INT NULL DEFAULT NULL,
  title VARCHAR(20) NOT NULL,
  metaTitle VARCHAR(40) NULL DEFAULT NULL,
  slug VARCHAR(20) NOT NULL,
  content TEXT NULL DEFAULT NULL,
  PRIMARY KEY (id))

  sp_help shopcategory

  CREATE TABLE shopcart (
  id INT NOT NULL,
  userId INT NULL DEFAULT NULL,
  sessionId VARCHAR(20) NOT NULL,
  token VARCHAR(40) NOT NULL,
  firstName VARCHAR(40) NULL DEFAULT NULL,
  middleName VARCHAR(40) NULL DEFAULT NULL,
  lastName VARCHAR(20) NULL DEFAULT NULL,
  mobile VARCHAR(20) NULL,
  email VARCHAR(20) NULL,
  line1 VARCHAR(20) NULL DEFAULT NULL,
  line2 VARCHAR(20) NULL DEFAULT NULL,
  city VARCHAR(20) NULL DEFAULT NULL,
  )

  sp_help shopcart

  CREATE TABLE shoporder(
  id INT NOT NULL ,
  userId BIGINT NULL DEFAULT NULL,
  sessionId VARCHAR(40) NOT NULL,
  token VARCHAR(20) NOT NULL,
  status INT NOT NULL DEFAULT 0,
  subTotal FLOAT NOT NULL DEFAULT 0,
  itemDiscount FLOAT NOT NULL DEFAULT 0,
  tax FLOAT NOT NULL DEFAULT 0,
  shipping FLOAT NOT NULL DEFAULT 0,
  total FLOAT NOT NULL DEFAULT 0,
  promo VARCHAR(40) NULL DEFAULT NULL,
  discount FLOAT NOT NULL DEFAULT 0,
  grandTotal FLOAT NOT NULL DEFAULT 0,
  firstName VARCHAR(40) NULL DEFAULT NULL,
  middleName VARCHAR(40) NULL DEFAULT NULL,
  lastName VARCHAR(20) NULL DEFAULT NULL,
  mobile VARCHAR(20) NULL,
  email VARCHAR(40) NULL,
  line1 VARCHAR(40) NULL DEFAULT NULL,
  line2 VARCHAR(20) NULL DEFAULT NULL,
  city VARCHAR(20) NULL DEFAULT NULL,
  )

  sp_help shoporder